apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: liquibase
          image: "{{ .Values.liquibase.image.repository }}:{{ .Values.liquibase.image.tag | default .Chart.AppVersion }}"
          command:
            - liquibase
            - update
            - "--changeLogFile=./changelog/changelog.xml"
            - "--url=jdbc:postgresql://$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_DB)"
            - "--username=$(DATABASE_USERNAME)"
            - "--password=$(DATABASE_PASSWORD)"
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-connect
                  key: host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-connect
                  key: port
            - name: DATABASE_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-connect
                  key: database
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-connect
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-connect
                  key: password
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: KEYCLOAK_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-iam-connection-urls
                  key: internal_auth
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-connect
                  key: host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-connect
                  key: port
            - name: DATABASE_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-connect
                  key: database
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-connect
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-database-connect
                  key: password
          livenessProbe:
            failureThreshold: 4
            initialDelaySeconds: 53
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 4
            initialDelaySeconds: 53
            periodSeconds: 5
            successThreshold: 2
            tcpSocket:
              port: http
            timeoutSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
