apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-iam-credentials
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
type: Opaque
data:
    KEYCLOAK_USER: "{{ .Values.credentials.username | b64enc }}"
    KEYCLOAK_PASSWORD: "{{ .Values.credentials.password | b64enc }}"
    {{- range $i, $s := (.Values.initialUsers) }}
    DOYOUEVENTRACK_FIRSTNAME_{{ $i }}: "{{ $s.firstname | b64enc }}"
    DOYOUEVENTRACK_LASTNAME_{{ $i }}: "{{ $s.lastname | b64enc }}"
    DOYOUEVENTRACK_EMAIL_{{ $i }}: "{{ $s.email | b64enc }}"
    DOYOUEVENTRACK_PASSWORD_{{ $i }}: "{{ $s.password | b64enc }}"
    {{- end }}