apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-iam-smtp-settings
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    revision: "{{ .Release.Revision }}"
type: Opaque
stringData:
  smtp.json: |-
            {
              "smtpServer" : {
                "password" : "{{ .Values.smtpServer.password }}",
                "replyToDisplayName" : "{{ .Values.smtpServer.replyToDisplayName }}",
                "starttls" : "{{ .Values.smtpServer.starttls }}",
                "auth" : "{{ .Values.smtpServer.auth }}",
                "port" : "{{ .Values.smtpServer.port }}",
                "host" : "{{ .Values.smtpServer.host }}",
                "replyTo" : "{{ .Values.smtpServer.replyTo }}",
                "from" : "{{ .Values.smtpServer.from }}",
                "fromDisplayName" : "{{ .Values.smtpServer.fromDisplayName }}",
                "ssl" : "{{ .Values.smtpServer.ssl }}",
                "user" : "{{ .Values.smtpServer.user }}"
              }
            }