## Builder: build eventlistener jar
FROM maven:3.8-jdk-11-slim AS builder
WORKDIR src
COPY . ./
RUN mvn package -Dmaven.compiler.executable=javac -Dmaven.test.skip=true -f ./plugins/event_listener

## Final image
FROM jboss/keycloak:11.0.2

USER root

# Script for adding users based on environment vars
COPY ./scripts/add-dyet-users.sh /srv/dyet/add-users.sh
RUN chmod 777 /srv/dyet/add-users.sh

USER jboss

# Settings
ENV PROXY_ADDRESS_FORWARDING=true

# Theme
COPY ./themes/DoYouEvenTrack /opt/jboss/keycloak/themes/FitTrack

# Import realm
COPY ./realm-export.json /tmp/realm-export.json
ENV KEYCLOAK_IMPORT="/tmp/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled"

# Plugin
COPY --from=builder /src/plugins/event_listener/target/event-listener.jar /opt/jboss/keycloak/standalone/deployments/